# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'SmarkPark' do
  # use_frameworks!

  # Pods for SmarkPark

  pod 'IQKeyboardManager'
  pod 'AFNetworking', '~> 3.0'
  pod "JSONModel"
  pod "MJRefresh"
  pod "AMapNavi"
  pod "AMapLocation"
  pod "AMapSearch"
  pod "Masonry"
  pod 'SVProgressHUD'
  pod 'MBProgressHUD', '~> 1.1.0'

end
